Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
Exception: これはエラーメッセージです。
